# Site settings
title: Mapsense.js
email: support@mapsense.co
description: > # this means to ignore newlines until "baseurl:"
  Mapsense.js is a JavaScript library for vector maps in the browser.
  It brings the scalability of tiled geographic datasets to the interactivity, control, and dynamism of D3. A D3 selection is maintained across incoming tiles, letting you set things like styles or interaction just once.
  Mapsense.js is based on the Polymaps API, but uses D3 to handle drawing and selection.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://mapsense.github.io/mapsense.js/" # the base hostname & protocol for your site

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "pageWithSidebar"

# Build settings
markdown: kramdown
